
#! /bin/bash

export POSTGRES_USER="xxx"
export POSTGRES_DBNAME="xx"
export POSTGRES_PASSWORD="xx"
export POSTGRES_USER_RO="xx"
export POSTGRES_PASSWORD_RO="xx"
export POSTGRES_SCHEMA_PUBLIC_FACING="xx"

export POSTGRES_CONNECTION_STRING="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@docker_db_manual_run:5432/$POSTGRES_DBNAME"
export POSTGRES_CONNECTION_STRING_RO="postgresql://$POSTGRES_USER_RO:$POSTGRES_PASSWORD_RO@docker_db_manual_run:5432/$POSTGRES_DBNAME"
