name: Add issue to project
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh project item-add 3 --owner LaCapitale --url "$URL"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_REPO: ${{ github.repository }}
          URL: ${{ github.event.issue.html_url}}